name: release

on:
  push:
    tags:
      - v*

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: goreleaser release
        run: make snapshot