name: Release

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  job1:
    runs-on: ${{ matrix.os }}
    env:
      GOARCH: ${{ matrix.arch }}
      CGO_ENABLED: ${{ matrix.cgo }}
      CPATH: ${{ matrix.cpath }}
      GODEBUG: cgocheck=2
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: amd64
            cgo: 1
            cpath: C:\Program Files (x86)\WinFsp\inc\fuse
          - os: ubuntu-latest
            arch: amd64
            cgo: 1
          - os: macos-10.15
            arch: amd64
            cgo: 1
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install go
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: 1.18.*

      - name: Install winfsp and winfsp-tests (Windows)
        if: runner.os == 'Windows'
        run: |
          $releases = Invoke-WebRequest https://api.github.com/repos/winfsp/winfsp/releases | `
           ConvertFrom-Json
          $asseturi = $releases[0].assets.browser_download_url | `
           Where-Object { $_ -match "winfsp-.*\.msi" }
          Invoke-WebRequest -Uri $asseturi -Out winfsp.msi
          Start-Process -NoNewWindow -Wait msiexec "/i winfsp.msi /qn INSTALLLEVEL=1000"
          $asseturi = $releases[0].assets.browser_download_url | `
           Where-Object { $_ -match "winfsp-tests-.*\.zip" }
          Invoke-WebRequest -Uri $asseturi -Out winfsp-tests.zip
          Expand-Archive -Path winfsp-tests.zip
          Copy-Item "C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll" winfsp-tests

      - name: Install FUSE (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -qq install libfuse-dev
          sudo apt-get -qq install libacl1-dev
          sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev libwebkit2gtk-4.0-37-gtk2

      - name: Install FUSE (macOS)
        if: runner.os == 'macOS'
        run: |
          # requires macos-10.15; does not work on macos-latest
          # see https://github.com/actions/virtual-environments/issues/4731
          brew install macfuse

      - name: Set git to use LF
        # make sure that line endings are not converted on windows
        # as gofmt linter will report that they need to be changed
        run: git config --global core.autocrlf false
      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install wails
        run: |
          GO111MODULE=on go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build
        run: make binary
  job2:
    runs-on: ubuntu-latest
    steps:
      - name : Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}